# Permalinks
permalink:           /:categories/:title

# Setup
title:               '@woahdae'
tagline:             life++
description:         >
  bikes, food, tech, etc
url:                 http://woahdae.com
paginate:            5
baseurl:             ""

# Assets
sass:
  style:            :compressed

# About/contact
author:
  name:              Woody Peterson
  url:               http://woahdae.com
  email:             woody.peterson@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

markdown: kramdown
highlighter: rouge
