# Permalinks
permalink:           pretty

# Setup
title:               '@woahdae'
tagline:             simple elevates
description:         >
  bikes, soil, tech, etc
url:                 http://woahdae.com
paginate:            5
baseurl:             ""

# Assets
sass:
  style:            :compressed

# About/contact
author:
  name:              Woody Peterson
  url:               http://woahdae.com
  email:             woody.peterson@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
